// Generated by gencpp from file ros_volume_estimation/ToggleProcessingResponse.msg
// DO NOT EDIT!


#ifndef ROS_VOLUME_ESTIMATION_MESSAGE_TOGGLEPROCESSINGRESPONSE_H
#define ROS_VOLUME_ESTIMATION_MESSAGE_TOGGLEPROCESSINGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_volume_estimation
{
template <class ContainerAllocator>
struct ToggleProcessingResponse_
{
  typedef ToggleProcessingResponse_<ContainerAllocator> Type;

  ToggleProcessingResponse_()
    : success(false)
    , message()  {
    }
  ToggleProcessingResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ToggleProcessingResponse_

typedef ::ros_volume_estimation::ToggleProcessingResponse_<std::allocator<void> > ToggleProcessingResponse;

typedef boost::shared_ptr< ::ros_volume_estimation::ToggleProcessingResponse > ToggleProcessingResponsePtr;
typedef boost::shared_ptr< ::ros_volume_estimation::ToggleProcessingResponse const> ToggleProcessingResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator1> & lhs, const ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator1> & lhs, const ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_volume_estimation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_volume_estimation/ToggleProcessingResponse";
  }

  static const char* value(const ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
;
  }

  static const char* value(const ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ToggleProcessingResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_volume_estimation::ToggleProcessingResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_VOLUME_ESTIMATION_MESSAGE_TOGGLEPROCESSINGRESPONSE_H
