// Generated by gencpp from file ros_volume_estimation/ToggleProcessingRequest.msg
// DO NOT EDIT!


#ifndef ROS_VOLUME_ESTIMATION_MESSAGE_TOGGLEPROCESSINGREQUEST_H
#define ROS_VOLUME_ESTIMATION_MESSAGE_TOGGLEPROCESSINGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_volume_estimation
{
template <class ContainerAllocator>
struct ToggleProcessingRequest_
{
  typedef ToggleProcessingRequest_<ContainerAllocator> Type;

  ToggleProcessingRequest_()
    : enabled(false)  {
    }
  ToggleProcessingRequest_(const ContainerAllocator& _alloc)
    : enabled(false)  {
  (void)_alloc;
    }



   typedef uint8_t _enabled_type;
  _enabled_type enabled;





  typedef boost::shared_ptr< ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ToggleProcessingRequest_

typedef ::ros_volume_estimation::ToggleProcessingRequest_<std::allocator<void> > ToggleProcessingRequest;

typedef boost::shared_ptr< ::ros_volume_estimation::ToggleProcessingRequest > ToggleProcessingRequestPtr;
typedef boost::shared_ptr< ::ros_volume_estimation::ToggleProcessingRequest const> ToggleProcessingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator1> & lhs, const ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator2> & rhs)
{
  return lhs.enabled == rhs.enabled;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator1> & lhs, const ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_volume_estimation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2815464f55ab63684cc1bc38072d0b9b";
  }

  static const char* value(const ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2815464f55ab6368ULL;
  static const uint64_t static_value2 = 0x4cc1bc38072d0b9bULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_volume_estimation/ToggleProcessingRequest";
  }

  static const char* value(const ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool enabled\n"
;
  }

  static const char* value(const ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enabled);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ToggleProcessingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_volume_estimation::ToggleProcessingRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "enabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enabled);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_VOLUME_ESTIMATION_MESSAGE_TOGGLEPROCESSINGREQUEST_H
