// Generated by gencpp from file ros_volume_estimation/ToggleProcessing.msg
// DO NOT EDIT!


#ifndef ROS_VOLUME_ESTIMATION_MESSAGE_TOGGLEPROCESSING_H
#define ROS_VOLUME_ESTIMATION_MESSAGE_TOGGLEPROCESSING_H

#include <ros/service_traits.h>


#include <ros_volume_estimation/ToggleProcessingRequest.h>
#include <ros_volume_estimation/ToggleProcessingResponse.h>


namespace ros_volume_estimation
{

struct ToggleProcessing
{

typedef ToggleProcessingRequest Request;
typedef ToggleProcessingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToggleProcessing
} // namespace ros_volume_estimation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_volume_estimation::ToggleProcessing > {
  static const char* value()
  {
    return "91b5d40c59e3059df49ed9dc7354ebfc";
  }

  static const char* value(const ::ros_volume_estimation::ToggleProcessing&) { return value(); }
};

template<>
struct DataType< ::ros_volume_estimation::ToggleProcessing > {
  static const char* value()
  {
    return "ros_volume_estimation/ToggleProcessing";
  }

  static const char* value(const ::ros_volume_estimation::ToggleProcessing&) { return value(); }
};


// service_traits::MD5Sum< ::ros_volume_estimation::ToggleProcessingRequest> should match
// service_traits::MD5Sum< ::ros_volume_estimation::ToggleProcessing >
template<>
struct MD5Sum< ::ros_volume_estimation::ToggleProcessingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_volume_estimation::ToggleProcessing >::value();
  }
  static const char* value(const ::ros_volume_estimation::ToggleProcessingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_volume_estimation::ToggleProcessingRequest> should match
// service_traits::DataType< ::ros_volume_estimation::ToggleProcessing >
template<>
struct DataType< ::ros_volume_estimation::ToggleProcessingRequest>
{
  static const char* value()
  {
    return DataType< ::ros_volume_estimation::ToggleProcessing >::value();
  }
  static const char* value(const ::ros_volume_estimation::ToggleProcessingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_volume_estimation::ToggleProcessingResponse> should match
// service_traits::MD5Sum< ::ros_volume_estimation::ToggleProcessing >
template<>
struct MD5Sum< ::ros_volume_estimation::ToggleProcessingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_volume_estimation::ToggleProcessing >::value();
  }
  static const char* value(const ::ros_volume_estimation::ToggleProcessingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_volume_estimation::ToggleProcessingResponse> should match
// service_traits::DataType< ::ros_volume_estimation::ToggleProcessing >
template<>
struct DataType< ::ros_volume_estimation::ToggleProcessingResponse>
{
  static const char* value()
  {
    return DataType< ::ros_volume_estimation::ToggleProcessing >::value();
  }
  static const char* value(const ::ros_volume_estimation::ToggleProcessingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_VOLUME_ESTIMATION_MESSAGE_TOGGLEPROCESSING_H
